name: Terraform Validate

on:
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-validate.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [ 'terraform/aws', 'terraform/azure' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Init (no backend)
        working-directory: ${{ matrix.dir }}
        run: terraform init -backend=false

      - name: Validate
        working-directory: ${{ matrix.dir }}
        run: terraform validate

